#!/usr/bin/env python3
# Copyright (c) 2026 The Jaeger Authors.
# SPDX-License-Identifier: Apache-2.0

"""Check and update required copyright + SPDX headers."""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import sys
from datetime import datetime

CURRENT_YEAR = datetime.today().year
ROOT = pathlib.Path(__file__).resolve().parents[2]

SCOPE_EXTENSIONS = {
    ".go",
    ".js",
    ".ts",
    ".py",
    ".sh",
    ".yaml",
    ".yml",
    ".mk",
}
SCOPE_PREFIX_FILENAMES = ("Makefile", "Dockerfile")

EXCLUDED_DIR_PARTS = {
    ".git",
    "vendor",
    "idl",
    "jaeger-ui",
}
EXCLUDED_PATH_FRAGMENTS = (
    "/internal/tools/",
    "/scripts/build/docker/debug/",
    "/mocks/",
)
EXCLUDED_FILE_SUFFIXES = (".pb.go",)
EXCLUDED_FILE_PREFIXES = ("_", ".")
HEADER_SCAN_LINES = 20

# Accept common historical variants (single year, year ranges/lists, optional
# trailing period) so existing valid Jaeger headers are not duplicated.
JAEGER_COPYRIGHT_RE = re.compile(
    r"Copyright \(c\)\s+\d{4}(?:[\s,/-]*\d{4})*\s+The Jaeger Authors\.?",
    re.IGNORECASE,
)
SPDX_RE = re.compile(r"SPDX-License-Identifier:\s*Apache-2\.0", re.IGNORECASE)
SHEBANG_RE = re.compile(r"^#!\s*/\S+")


def _resolve_path(path: pathlib.Path) -> pathlib.Path:
    try:
        return path.resolve(strict=False)
    except OSError:
        return path


def _path_in_scope(path: pathlib.Path) -> bool:
    resolved = _resolve_path(path)
    try:
        rel = resolved.relative_to(ROOT)
    except ValueError:
        # Explicit args may include absolute or ../ paths outside repo root.
        return False

    name = resolved.name

    if name.startswith(EXCLUDED_FILE_PREFIXES):
        return False
    if any(name.endswith(suffix) for suffix in EXCLUDED_FILE_SUFFIXES):
        return False
    if name.startswith("mocks"):
        return False

    rel_posix = rel.as_posix()
    rel_wrapped = f"/{rel_posix}/"
    if any(fragment in rel_wrapped for fragment in EXCLUDED_PATH_FRAGMENTS):
        return False
    if any(part in EXCLUDED_DIR_PARTS for part in rel.parts):
        return False

    if resolved.suffix in SCOPE_EXTENSIONS:
        return True
    if any(name.startswith(prefix) for prefix in SCOPE_PREFIX_FILENAMES):
        return True
    return False


def _comment_prefix(path: pathlib.Path) -> str:
    if path.suffix in {".go", ".js", ".ts"}:
        return "//"
    return "#"


def _header_lines(path: pathlib.Path) -> list[str]:
    prefix = _comment_prefix(path)
    return [
        f"{prefix} Copyright (c) {CURRENT_YEAR} The Jaeger Authors.\n",
        f"{prefix} SPDX-License-Identifier: Apache-2.0\n",
    ]


def _insertion_index(lines: list[str]) -> int:
    if not lines:
        return 0
    if SHEBANG_RE.match(lines[0]):
        return 1
    if "Code generated by" in lines[0]:
        return 1
    return 0


def _ensure_trailing_blank(lines: list[str], index: int) -> None:
    if index >= len(lines):
        lines.append("\n")
        return
    if lines[index].strip():
        lines.insert(index, "\n")


def _copyright_line_index(lines: list[str]) -> int | None:
    for i, line in enumerate(lines[:HEADER_SCAN_LINES]):
        if JAEGER_COPYRIGHT_RE.search(line):
            return i
    return None


def _update_file(path: pathlib.Path, check_only: bool) -> bool:
    content = path.read_text(encoding="utf-8")
    lines = content.splitlines(keepends=True)
    head = "".join(lines[:HEADER_SCAN_LINES])

    has_copyright = JAEGER_COPYRIGHT_RE.search(head) is not None
    has_spdx = SPDX_RE.search(head) is not None
    if has_copyright and has_spdx:
        return False

    if check_only:
        return True

    new_lines = list(lines)

    to_insert: list[str] = []
    header = _header_lines(path)
    if not has_copyright:
        to_insert.append(header[0])
    if not has_spdx:
        to_insert.append(header[1])

    copyright_idx = _copyright_line_index(new_lines)
    if has_copyright and not has_spdx and copyright_idx is not None:
        insert_idx = copyright_idx + 1
        if insert_idx <= len(new_lines):
            new_lines[insert_idx:insert_idx] = [header[1]]
            _ensure_trailing_blank(new_lines, insert_idx + 1)
            path.write_text("".join(new_lines), encoding="utf-8")
            return True

    idx = _insertion_index(new_lines)

    if (
        idx > 0
        and idx < len(new_lines)
        and new_lines[idx - 1].strip()
        and new_lines[idx].strip()
    ):
        new_lines.insert(idx, "\n")
        idx += 1

    new_lines[idx:idx] = to_insert
    _ensure_trailing_blank(new_lines, idx + len(to_insert))

    path.write_text("".join(new_lines), encoding="utf-8")
    return True


def _should_skip_dir(rel_dir: pathlib.Path, dirname: str) -> bool:
    if dirname in EXCLUDED_DIR_PARTS:
        return True
    if dirname.startswith(EXCLUDED_FILE_PREFIXES):
        return True
    if dirname.startswith("mocks"):
        return True

    candidate = (rel_dir / dirname).as_posix()
    wrapped = f"/{candidate}/"
    return any(fragment in wrapped for fragment in EXCLUDED_PATH_FRAGMENTS)


def _iter_source_files() -> list[pathlib.Path]:
    paths: list[pathlib.Path] = []

    for dirpath, dirnames, filenames in os.walk(ROOT):
        current_dir = pathlib.Path(dirpath)
        rel_dir = current_dir.relative_to(ROOT)

        dirnames[:] = [
            dirname
            for dirname in dirnames
            if not _should_skip_dir(rel_dir, dirname)
        ]

        for filename in filenames:
            path = current_dir / filename
            if path.is_file() and _path_in_scope(path):
                paths.append(path)

    return sorted(paths)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Check or add required Jaeger license headers."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Only report files missing required headers.",
    )
    parser.add_argument(
        "files",
        nargs="*",
        help="Optional files to process; defaults to repository scope.",
    )
    args = parser.parse_args()

    if args.files:
        files = [pathlib.Path(f) if pathlib.Path(f).is_absolute() else ROOT / f for f in args.files]
    else:
        files = _iter_source_files()

    changed: list[str] = []
    for path in files:
        if not path.exists() or not path.is_file() or not _path_in_scope(path):
            continue
        if _update_file(path, check_only=args.check):
            changed.append(path.relative_to(ROOT).as_posix())

    if changed:
        action = "Missing headers" if args.check else "Updated headers"
        print(f"{action} in {len(changed)} file(s):")
        for name in changed:
            print(name)

    if args.check and changed:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
